//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtavBlog.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtavBlog.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کاربران.
        /// </summary>
        public static string APP_STRINGKEYS_Account_Index {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Account_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string APP_STRINGKEYS_Account_Login {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Account_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربری خود را وارد کنید.
        /// </summary>
        public static string APP_STRINGKEYS_Account_Login_Subtitle {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Account_Login_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string APP_STRINGKEYS_Account_LogOff {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Account_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری.
        /// </summary>
        public static string APP_STRINGKEYS_Account_Profile {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Account_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انجام عملیات مورد مشکلی بوجود آمده است.
        /// </summary>
        public static string APP_STRINGKEYS_Message_Failure {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Message_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری / رمز عبور اشتباه است.
        /// </summary>
        public static string APP_STRINGKEYS_Message_LoginFailed {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Message_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گره موردنظر قابل ویرایش نیست.
        /// </summary>
        public static string APP_STRINGKEYS_Message_NodeCannotEdit {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Message_NodeCannotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد.
        /// </summary>
        public static string APP_STRINGKEYS_Message_Success {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما غیرفعال شده است.
        /// </summary>
        public static string APP_STRINGKEYS_Message_Suspend {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Message_Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        public static string APP_STRINGKEYS_Password {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        public static string APP_STRINGKEYS_Return {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف.
        /// </summary>
        public static string APP_STRINGKEYS_Row {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        public static string APP_STRINGKEYS_Save {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت نام.
        /// </summary>
        public static string APP_STRINGKEYS_SignupDate {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_SignupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [بدون تغییر].
        /// </summary>
        public static string APP_STRINGKEYS_Unchanged {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Unchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string APP_STRINGKEYS_Username {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده در برای فیلد {0} در فرمت مناسب نیست.
        /// </summary>
        public static string APP_STRINGKEYS_Validation_BadFormat {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Validation_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات فیلد {0} قبلا وارد شده است.
        /// </summary>
        public static string APP_STRINGKEYS_Validation_Remote_Uniqueness {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Validation_Remote_Uniqueness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پر کردن فیلد {0} الزامی است.
        /// </summary>
        public static string APP_STRINGKEYS_Validation_Required {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول فیلد {0} باید میان {1} و {2} باشد.
        /// </summary>
        public static string APP_STRINGKEYS_Validation_Stringlength {
            get {
                return ResourceManager.GetString("APP_STRINGKEYS_Validation_Stringlength", resourceCulture);
            }
        }
    }
}
